#include "mongoose_dependencies/mongoose.h"

// Connection event handler function
static void ev_handler(struct mg_connection *c, int ev, void *ev_data) {
  if (ev == MG_EV_HTTP_MSG) {  // New HTTP request received
    printf("Received HTTP request\n");
    printf("URI: %.*s\n", (int) ((struct mg_http_message *) ev_data)->uri.len,
           ((struct mg_http_message *) ev_data)->uri.buf);
    struct mg_http_message *hm = (struct mg_http_message *) ev_data;  
    
    // Check for REST API calls first
    if (mg_match(hm->uri, mg_str("/api/hello"), NULL)) {              
      mg_http_reply(c, 200, "", "{%m:%d}\n", MG_ESC("status"), 1);    
      return; 
    }
    if (mg_match(hm->uri, mg_str("/api/buy"), NULL)) {
      
      // Ensure they are actually sending data (POST request)
      if (!mg_match(hm->method, mg_str("POST"), NULL)) {
        mg_http_reply(c, 405, "", "{\"error\": \"Method not allowed, use POST\"}\n");
        return; 
      }

      // Set up variables to hold parsed data
      char symbol[16] = {0};       // AAPL, TSLA, etc.
      char order_type[16] = {0};   // limit, market, etc.
      double shares = 0;           // num of shares
      double user_id = 0;          // user id of user placing order

      // Extract the data from the request body (hm->body)
      char *symbol_ptr = mg_json_get_str(hm->body, "$.symbol");
      char *type_ptr = mg_json_get_str(hm->body, "$.orderType");

      if (symbol_ptr) {
          snprintf(symbol, sizeof(symbol), "%s", symbol_ptr);
      }
      if (type_ptr) {
          snprintf(order_type, sizeof(order_type), "%s", type_ptr);
      }
      mg_json_get_num(hm->body, "$.shares", &shares);
      mg_json_get_num(hm->body, "$.userId", &user_id);

      printf("Order received: User %d wants to buy %f shares of %s (%s)\n", 
             (int)user_id, shares, symbol, order_type);

      // send a success response back to React
      mg_http_reply(c, 200, "Content-Type: application/json\r\n", 
                    "{\"status\": \"success\", \"message\": \"Order received\"}\n");
      return; 
    }
    // If they just go to domain then serve the app
    struct mg_http_serve_opts opts = {0};
    
    // the output folder generated by npm run build
    opts.root_dir = "frontend/dist"; 
    
    // If a user refreshes on a custom React route (e.g., /about), 
    // return to base react app so react router can handle it
    opts.page404 = "frontend/dist/index.html";
    
    // actually serve the requested resource 
    mg_http_serve_dir(c, hm, &opts);
  }
}

int main() {
  struct mg_mgr mgr;  
  mg_mgr_init(&mgr);  
  mg_http_listen(&mgr, "http://0.0.0.0:8000", ev_handler, NULL);
  for (;;) {
    mg_mgr_poll(&mgr, 1000);  
  }
  return 0;

  
}